### ISSUE TITLE
Past dates and dates out of range are not fully disabled

### ISSUE THREAD

**Issue by Nicero** [fengyuanchen/datepicker#1]
I noticed that althought I use the javascript function to disable past dates, only the dates of the present month are actually disabled and not clickable. The dates of the past month, months or years may by clicked althought they appear grayed. 
This happens also when the user wants to disable certain days or set a range of valid dates: dates are actually disabled only for the present month, but not for the past or future month/months or year/years. You can easily check the issue in the demos 'Disable the past days', 'Disable all of the Wednesday' and 'Set a date range'.

**Comment by fengyuanchen** [comment]
I'm sorry, we don't support this right now, we just support to disable some special date by `isDisabled` function, but not support to disable date range.

**Comment by Nicero** [comment]
Sorry, maybe I did not explained well myself, but this in my opinion is a bug: when "disabled past dates" is used only the past dates of the present month are actually disabled, the dates of the previous months are grayed but are still clickable.

**Comment by fengyuanchen** [comment]
I see, thank you very much~

**Comment by djkirby** [comment]
+1 @Nicero I am facing the same issue

**Comment by fengyuanchen** [comment]
This feature had been supported with `startDate` and `endDate` options in the [v0.2.0](https://github.com/fengyuanchen/datepicker/releases/tag/v0.2.0).
