### ISSUE TITLE
Multiple values for isDisabled?

### ISSUE THREAD

**Issue by jq1106** [fengyuanchen/datepicker#10]
I'm trying to disable weekends, while having a minDate set but nothing I seem to do works. Is this not possible, or am I doing something wrong?

**Comment by fengyuanchen** [comment]
```js
$().datepicker({
  isDisabled: function(date) {
    return (date.getDay() === 6 || date.getDay() === 0) ? true : false;
  }
});
```

**Comment by fengyuanchen** [comment]
Try the `startDate` and `endDate` in the v0.2.0 please.
