### ISSUE TITLE
Check if a date has been selected

### ISSUE THREAD

**Issue by lspoor** [fengyuanchen/datepicker#102]
I'm using an input to connect my date picker to. I need a way to to check once the datepicker has been opened and a date has been selected I can remove a class off the input.

For example for basic text inputs etc I'm using the following code. Except this doesn't work because the blur function cancels when clicking on the datepicker and also the datepicker doesn't actually store the date value within the input
```
$('input, select, textarea').blur(function(){
        val = $(this).val();
        if(val == '') {
            $(this).addClass('error');
            $(this).removeClass('no-error');
        } else {
            $(this).addClass('no-error');
            $(this).removeClass('error');
        }
    });
```

**Comment by fengyuanchen** [comment]
This is not an issue about this project, fix it by yourself.
