### ISSUE TITLE
show() method didn't work

### ISSUE THREAD

**Issue by alaa-jad** [fengyuanchen/datepicker#103]
I want the datepicker to apear when I click on a button, I used $().datepicker('show') but the datepicker stay hidden

**Comment by fengyuanchen** [comment]
This is not an issue about this project, fix it by yourself.

**Comment by alaa-jad** [comment]
Could you please tell me how to fix the code and use the show method right?

**Comment by mbibko** [comment]
You need to use stopPropagation method. Example:
$('.icon-calendar').on('click', function(e) {
  e.stopPropagation();
  $('.js-datepicker').datepicker('show');
})
