### ISSUE TITLE
date picker not show in poup modal Bootstrap 4 !

### ISSUE THREAD

**Issue by henrytran9x** [fengyuanchen/datepicker#105]
Hi I used date picker for show date in text input Bootstrap 4 but text field not show date picker. I tried text field out popup which done . How to fix date picker in popup modal ?

Thank you !

**Comment by fengyuanchen** [comment]
https://github.com/fengyuanchen/datepicker/blob/master/examples/datepicker-in-modal.html

**Comment by reflectaky** [comment]
not showing

**Comment by fengyuanchen** [comment]
The link has been edited.
