### ISSUE TITLE
move away from jQuery to pure ES5/6

### ISSUE THREAD

**Issue by DanielRuf** [fengyuanchen/datepicker#107]
The minified version should not be bundled with jQuery as this would overwrite previous plugins and remove them from the $/jQuery namespace.

**Comment by fengyuanchen** [comment]
bundled with jQuery? What do you really mean?

**Comment by DanielRuf** [comment]
I mean the jQuery import at the top. In this form webpack and other bundlers always pull jQuery in, for every entry point.

Generally it makes more sense to move away from jQuery and transpile to pure ES5. This dependency makes it hard to use it in specific projects.

**Comment by fengyuanchen** [comment]
You are so fun. This is just a jQuery plugin.

**Comment by DanielRuf** [comment]
Hm, ok. I hoped we could move all dependencies and projects away from jQuery which is totally bloated. Fine, we'll switch to another datepicker.

Have a great weekend!
