### ISSUE TITLE
do not use --brand-color

### ISSUE THREAD

**Issue by DanielRuf** [fengyuanchen/datepicker#108]
When importing and building the file with node-sass it can't compile the css file (well, this is not css) as the var is not a valid color for Sass.

**Comment by fengyuanchen** [comment]
Why not just compile the `dist/datepicker.css` file?!

**Comment by DanielRuf** [comment]
Generally this is not a scss file so sass still fails. Also variables in this form are not supported there.

This library should not require specific solutions like postcss and should be compilable with Sass or any other precompiler.

**Comment by fengyuanchen** [comment]
You are so fun.

**Comment by DanielRuf** [comment]
Ok. Or do you recommend importing a postcss loader? How should I separate your css file in src from normal css files in the webpack streams? Or just pipe them all through all precompilers?

**Comment by fengyuanchen** [comment]
Please just use the public files in the `dist` directory as the `src` directory only for own development.

**Comment by DanielRuf** [comment]
Ok. Thanks for the reply. This could be a valid solution for the projects which still rely on jQuery.
