### ISSUE TITLE
How to restrict years range in date picker?

### ISSUE THREAD

**Issue by castilloedwin** [fengyuanchen/datepicker#109]
I would like to know if it is possible to have the years above the current one not shown. For example, if we are in 2017, I do not want it to show 2018 onwards. Thanks in advance.

**Comment by gerchomat** [comment]
You can't do that at the moment.

But you could set and endDate and hide all disabled days via css:
https://github.com/fengyuanchen/datepicker/blob/master/README.md#enddate
