### ISSUE TITLE
onSelect option

### ISSUE THREAD

**Issue by anoopmd** [fengyuanchen/datepicker#11]
I had a scenario where I had to show the datepicker onclick of a button instead of an input element.
The Issue was that the date was getting reflected in the button. I solved the problem by making the font size 0. 

But I had to update the input box upon date change in the button. This was difficult since the button elements did not fire change events when the text changed.

It would be great if there is an option for callback when the date is selected.

Ex : 
$(".datepicker").datepicker({
  onSelect : function(date){
     // Do something with the date.
     // Like updating the textbox (In my case)
  }
});

**Comment by fengyuanchen** [comment]
You can try `pick.datepicker` event in the v0.2.0 for this.
