### ISSUE TITLE
question on disable date

### ISSUE THREAD

**Issue by quasiperfect** [fengyuanchen/datepicker#111]
hi

first let me thank you for you script is really nice

second some questions

can i disable all dates and allow some ?
or can i disable one or more date between startDate and endDate ?

**Comment by fengyuanchen** [comment]
Please check out the [`filter`](https://github.com/fengyuanchen/datepicker#filter) option for more information.

**Comment by quasiperfect** [comment]
@fengyuanchen 

i tried to use the function like you said but i think there is a bug somewhere
i have an active month that should not be active
here is my codepen
https://codepen.io/quasiperfect/pen/pdXqRj
