### ISSUE TITLE
can't choose the inital month

### ISSUE THREAD

**Issue by meniac** [fengyuanchen/datepicker#113]
i can't choose the inital month, when the format is "mm/yyyy"
https://fengyuanchen.github.io/datepicker/
![1](https://user-images.githubusercontent.com/23456001/33232210-df00ccc4-d23c-11e7-9657-3664e15b3d8c.png)

**Comment by fengyuanchen** [comment]
I don't understand what you mean...

**Comment by ckruppe** [comment]
Have the same problem. If you use only the month picker and set an initial date of lets say 04/2018 you cant go back to that date if you choosed another.

To Reproduce:

1.) init an datepicker with: 
```
$().datepicker({
    format: this.props.format,
    startView: 1,
    weekStart: 1,
    date: new Date('2018', 3)
})
```
2.) Choose another month than the default.
3.) Try to choose the default again. You will see that the date does not change. Also in the pick.datepicker event the e.date is the in step 2 choosed month.
