### ISSUE TITLE
wrong condition for disabled years and months in combination with filtered

### ISSUE THREAD

**Issue by quasiperfect** [fengyuanchen/datepicker#116]
when filtered is used to disable days if you don't have the first day of a month active the script considers the month inactive and it cascades to years

code pen here (the years view and the months view is wrong)
https://codepen.io/quasiperfect/pen/KyjYdP

**Comment by matthieudanet** [comment]
Hi !
I have the same kind of problem when I try to use the filter function given as an example.
Thanks

**Comment by fengyuanchen** [comment]
It is too inefficient if fix this bug:
- In the `months` view, the `filter` function should be called 12 * 30 times.
- In the `years` view, the `filter` function should be called 12 * 365 times.

**Comment by dimovelev** [comment]
I would suggest to pass two parameters to the filter function - the view (0, 1, 2) and a date. In case of months, the day is the first day of the month, in case of years, the first day of the year. the filter code can then decide what to do.

**Comment by dimovelev** [comment]
are you interested in a PR where the filter method is called with a second parameter with the value day, month or year depending on the context where it is being used? it is just a few lines of changes and does fix this issue for me at least.

**Comment by dimovelev** [comment]
my suggestion as how to fix the issue is in this pull request - https://github.com/fengyuanchen/datepicker/pull/151
