### ISSUE TITLE
support month disabled

### ISSUE THREAD

**Issue by tenbamboo** [fengyuanchen/datepicker#12]
can you support month disabled 
like:
$.fn.datepicker.setDefaults({
		autoClose:true,
		dateFormat:'yyyy-mm',
               isDisabled: function(date) {
	        return date.valueOf() < new Date() ? true : false; //before now  enable 
	    }
});
$("#selectStartDate").datepicker();

**Comment by fengyuanchen** [comment]
With v0.2.0:
```js
$().datepicker({
  filter: function (date) {
    if (date.getMonth() < 3) {
      return false; // Disable January, February and March
    }
  }
})
```
