### ISSUE TITLE
Position problem in scrollable modal

### ISSUE THREAD

**Issue by yuduxyz** [fengyuanchen/datepicker#121]
When datepicker is placed in a scrollable modal, it doesn't scroll along with other contents. For example, in examples/datepicker-in-modal.html, we set line 30-34 as below:

```html
<div class="modal-body" style="height: 200px; overflow: auto">
    <div style="height: 500px"></div>
    <input type="text" class="form-control" data-toggle="datepicker">
    <div style="height: 500px"></div>
</div>
```

then, scroll the modal, we can get:
![image](https://user-images.githubusercontent.com/9818716/35031094-7fe43a1c-fb9c-11e7-91a7-b144ba23b792.png)

It would be better if datepicker scrolls together with the input box.

**Comment by fengyuanchen** [comment]
Please scroll the modal container instead of the modal body...

**Comment by yuduxyz** [comment]
I'm afraid I didn't understand what you mean. Could you please give an example?

**Comment by fengyuanchen** [comment]
```css
.modal {
  overflow: auto;
}

.modal-body {
  overflow: visible;
}
```

**Comment by yuduxyz** [comment]
Hi, fengyuan

Thanks for your reply. I've tried your proposal, unfortunately, it doesn't work either.
I've created a demo here: https://codepen.io/yuduxyz/project/editor/DYyjva#0. Would you please give it a try?

**Comment by fengyuanchen** [comment]
I know what you mean now.

**Comment by LorenzV** [comment]
My temp solution is changing the library code so you can have a container without it being inline. You only need to change 2 lines.

I did it in the minified version because i was too lazy to switch.

```
i.input?e(i.container||t).append(a.addClass("datepicker-inline"))
i.container?e(i.container||t).append(a.addClass("datepicker-inline"))
```
and
```
i.removeClass(I).addClass(p).css({top:u,left:d,zIndex:parseInt(t.zIndex,10)})
i.removeClass(I).addClass(p).css(t.container ? {top:50} : {top:u,left:d,zIndex:parseInt(t.zIndex,10)})
```

**Comment by jokero158** [comment]
`
.datepicker-container{
	position: fixed;
	opacity: 0;
}
`

```
        $('[data-toggle="datepicker"]').on('show.datepicker', function (e) {

          setTimeout(function(){
            $('body').find('.datepicker-container').css({
             'top': $(e.target).offset().top - $(window).scrollTop() + 50,
             'opacity': 1
            })

          })
        });
```

Welcome

**Comment by tofikabdullayev** [comment]
`.datepicker-container{ position: fixed; opacity: 0; }`

```
        $('[data-toggle="datepicker"]').on('show.datepicker', function (e) {

          setTimeout(function(){
            $('body').find('.datepicker-container').css({
             'top': $(e.target).offset().top - $(window).scrollTop(), // Don't forget to add margins of target Exp.: +50
             'opacity': 1
            })

          })
        });
```
Welcome

**Comment by kumararunac** [comment]
tried but still am facing the issue. Can u plz elaborate

**Comment by Nagarajan1605** [comment]
Is this issue resolved. What change we have to made it. Is that change to be add in datetimepicker.js or css. Please tell us where to include and what to include.

**Comment by mach64ram** [comment]
You may try this

/* Check positioning to remain on screen. */
	_checkOffset: function( inst, offset, isFixed ) {
		var dpWidth = inst.dpDiv.outerWidth(),
			dpHeight = inst.dpDiv.outerHeight(),
			inputWidth = inst.input ? inst.input.outerWidth() : 0,
			inputHeight = inst.input ? inst.input.outerHeight() : 0,
			viewWidth = document.documentElement.clientWidth + ( isFixed ? 0 : $( document ).scrollLeft() ),
			viewHeight = document.documentElement.clientHeight + ( isFixed ? 0 : $( document ).scrollTop() );

		offset.left -= ( this._get( inst, "isRTL" ) ? ( dpWidth - inputWidth ) : 0 );
		offset.left -= ( isFixed && offset.left === inst.input.offset().left ) ? $( document ).scrollLeft() : 0;
		
		//----- ORGINAL CODE -----//
		//offset.top -= ( isFixed && offset.top === ( inst.input.offset().top + inputHeight ) ) ? $( document ).scrollTop() : 0;
		
		//----- MY SOLUTION -----//
		offset.top -= ( isFixed && ( $(document).scrollTop() > 0 ) ) ? $(document).scrollTop() : 0;
		
		// Now check if datepicker is showing outside window viewport - move to a better place if so.
		offset.left -= Math.min( offset.left, ( offset.left + dpWidth > viewWidth && viewWidth > dpWidth ) ?
			Math.abs( offset.left + dpWidth - viewWidth ) : 0 );
		offset.top -= Math.min( offset.top, ( offset.top + dpHeight > viewHeight && viewHeight > dpHeight ) ?
			Math.abs( dpHeight + inputHeight ) : 0 );
		
		return offset;
	}

**Comment by LohithaYalavarthi** [comment]
Any updates on this?

**Comment by chiragnsuthar** [comment]
i m getting same issue on scroll position not changed

**Comment by gadasandula** [comment]
is this issue resolved can you please tell me the changes
