### ISSUE TITLE
How to close calendar when another one is opened?

### ISSUE THREAD

**Issue by youradds** [fengyuanchen/datepicker#127]
I have a from/to date input on my page. Both have a datepicker() assigned:

```
    $('input.date-from-to-top').datepicker({  language: 'fr', autoHide: true,
        filter: function(date) {
            if (date < new Date()) {
              return false;
            }
        }
    });
```

How do I tell it to close the datepicker when another one is opened? I tried hooking in on:
```

$(document).on('show.datepicker', function (e) {

})
```

...but obviously it has already shown by then (so doing a **hide()** actually causes the current one not to open ;))

Thanks

Andy

**Comment by fengyuanchen** [comment]
Why not just bind the `show` event to the target input?!
