### ISSUE TITLE
inline calendar hide after pick a day

### ISSUE THREAD

**Issue by ayophanz** [fengyuanchen/datepicker#128]
I want to remain the calendar not to hide after clicking day,

**Comment by fengyuanchen** [comment]
Do you set the `autoHide` option to `false`?

**Comment by sassoli** [comment]
I also notice that `autoHide` doesn't work if `inline: true`...

**Comment by PieterxJan** [comment]
I had the same issue and fixed it by adding `event.preventDefault()`. 

The resulting code that works for me is the following:

```
jQuery('#js-datepickMe').datepicker({
    inline: true,
}).on('pick.datepicker', function (event) {
    event.preventDefault();
    console.log(event.date);
});
```
