### ISSUE TITLE
first and last year get muted class

### ISSUE THREAD

**Issue by fritzmg** [fengyuanchen/datepicker#130]
![screenshot-2018-3-26 datepicker](https://user-images.githubusercontent.com/4970961/37910353-9d4ecf8a-310d-11e8-8198-1d13c8e81a48.png)

The first and last year when selecting the year always get the `muted` CSS class. What is the reason behind this? I can't think of any reason why the first and last year would be different in this case. It makes sense for the `day` view where the days not belonging to the current month are `muted` - however, the first and last year in the `year` view shouldn't have any special meaning, should they? Just like the first and last month of the `month` view do not have any special meaning.

**Comment by fengyuanchen** [comment]
You are right.
