### ISSUE TITLE
Set start date/end date does not change the picked date is its disabled

### ISSUE THREAD

**Issue by saniaalex** [fengyuanchen/datepicker#136]
If I have a picked date of say 04/2/2018 and I set the start date of calendar to 04/10/2018, then the picked date should change to 04/10/2018 as well, because otherwise the picked date is a disabled date. Is there anything I can add to my script to make that work ?

**Comment by deybyd182** [comment]
Hi there! I know this is an old question but I want to help you!

I've the same problem and I solved making this:

```
$('#calendar').datepicker('setStartDate', '04/10/2018');
$('#calendar').datepicker('setDate', '04/10/2018');
```

I hope this works for you as you expect!

**Comment by fengyuanchen** [comment]
This might have been fixed.
