### ISSUE TITLE
Cannot set initial month

### ISSUE THREAD

**Issue by nzmuzzer** [fengyuanchen/datepicker#144]
I want the input blank on page load but for the initial calendar to begin six months from today, but it defaults to the current month and it seems there is no method to alter this.

I can get it to have October as the initial view rather than this month (April) but to achieve this I have to setDate to October, but I don't want an initial date set, just the initial view to be October

Thanks

**Comment by fengyuanchen** [comment]
Just use the `setDate` to change the default date.

**Comment by nzmuzzer** [comment]
I tried that but it sets the date in the input which I did not want. I've got past that now by clearing the input after calling setDate(). Thx for the reply
