### ISSUE TITLE
language option doesn't work

### ISSUE THREAD

**Issue by imkimchi** [fengyuanchen/datepicker#155]
I don't think It's a dependency error since I loaded `datepicker.js` and `datepicker.css` successfully and seems everything works fine except `language` option.

**html**
```
<b-form-input data-toggle="datepicker" type="text" placeholder="날짜 선택"></b-form-input>
```

**js**
```
$('[data-toggle="datepicker"]').datepicker({
    language: 'ko-KR',
    autoPick: true
});
```

**Comment by fengyuanchen** [comment]
Did you load the language file ([`i18n/datepicker.ko-KR.js`](https://github.com/fengyuanchen/datepicker/blob/master/i18n/datepicker.ko-KR.js))?

**Comment by imkimchi** [comment]
@fengyuanchen didn't know i had to load the language file manually, Thanks for help :)
