### ISSUE TITLE
Disable certain dates

### ISSUE THREAD

**Issue by Maximoy** [fengyuanchen/datepicker#160]
I have integrated your datepicker with my new website project. It works great. Thanks.
Just one thing I am not able to do yet:
(I am not an IT person. I am sorry if I bother you with this question).
I would need to disable December 24th (Christmas Eve) and Dec 31 (New Years Eve). Every year.
How should I write the code? I know how to disable lets say the 31st:

 filter: function (date) {
    if (date.getDate() === 31) {
      return false; 
    }
  },  

But do not know how to write the code to disable Dec 31 and Dec 24.
I would really appreciate your help.
Many thanks.

Maximo

**Comment by fengyuanchen** [comment]
```js
$().datepicker({
  filter: function(date) {
    if (date.getMonth() === 11 && [24, 31].includes(date.getDay())) {
      return false;
    }
  }
});
```

**Comment by JPBelley** [comment]
Would it be possible to add a specific class to these dates ?

**Comment by fengyuanchen** [comment]
@JPBelley Not support that. You can use the built-in `disabled` class.

**Comment by dimitrikrukov** [comment]
hi, I've been able to integrate your plugin with my web app but I want to disable dates after 7 days.
So from present day + 6 should be active then the rest should be disabled
