### ISSUE TITLE
Disable Dec 24 and Dec 31

### ISSUE THREAD

**Issue by Maximoy** [fengyuanchen/datepicker#162]
Hi,
I have sent this issue before and got and answer (thank you) with the code, but when I tested it did not work..
This is the script I have. Any ideas?

 <script>
    $(function() {
      $('[data-toggle="datepicker"]').datepicker({
        filter: function(date) {
    if (date.getMonth() === 11 && [24, 31].includes(date.getDay())) {
      return false;
    }
  }  
      });    
    });      
  </script>

**Comment by webdo** [comment]
It may be a bit late but to fix your problem just replace "date.getDay()" by "date.getDate()";

`$(function() { $('[data-toggle="datepicker"]').datepicker({ filter: date => { if (date.getMonth() === 11 && [24, 31].includes(date.getDate())) { return false; } } }); });`

**Comment by Maximoy** [comment]
Great. Thank you!!
