### ISSUE TITLE
Current month is not localized as expected

### ISSUE THREAD

**Issue by solsticedhiver** [fengyuanchen/datepicker#163]
Say you use datepicker in a locale (by example fr-FR).

Then, the current month is not localized.
See for yourself : [https://jsfiddle.net/vL407cs8/4/](https://jsfiddle.net/vL407cs8/4/)

I have not tested this bug with another locale but I except it to be the same.

**Comment by fengyuanchen** [comment]
It works as expected, just see the i18n file: https://rawgit.com/fengyuanchen/datepicker/master/i18n/datepicker.fr-FR.js

**Comment by solsticedhiver** [comment]
Ok. Sorry. I never saw Jun as month in french.

Look at the [wikipedia page](https://fr.wikipedia.org/wiki/Mois). I would suggest you to use the "**abbréviation courante**" column.

What you are using are 3 letters codes I never saw before. And you miss the accent.

**Comment by fengyuanchen** [comment]
Most of the i18n files are provided by other contributors. You can change it (PR) if you think you have a better terminology.

**Comment by solsticedhiver** [comment]
> Better

 What is that supposed to mean ? I am trying to be as neutral as possible. And providing source to back my "terminology"

In fact, I don't know why you are reinventing the wheel here as this is already defined in javascript. Just take a look at

    > new Date().toLocaleString('fr-FR', {'month': 'short'})
    "juin"
    > new Date('2018-04-16T15:15:15').toLocaleString('fr-FR', {'month':'short'})
    "avr."
   > // and so on

This is exactly as quoted from wikipedia. If I make a PR this will be to remove those i18n file and rely on internal js string locale already defined.

My guess is that js support more locale that yours 24 ones.
