### ISSUE TITLE
Filter ctx is undefined

### ISSUE THREAD

**Issue by Vinze** [fengyuanchen/datepicker#164]
Am I doing something wrong or did I just found a bug? See the following example:

```js
$('[data-toggle="datepicker"]').datepicker({
    filter: function(date, ctx) {
        console.log(date, ctx)
        return true;
    }
});
```

This logs the following: ``Date 2018-05-26T22:00:00.000Z undefined``

Why is ctx undefined? According to the documentation this should be set the one of the following: *The context is a string with one of the values - day, month or year.* 

I am using the following files:

- datepicker/dist/datepicker.min.js
- datepicker/dist/datepicker.min.css

**Comment by fengyuanchen** [comment]
The `ctx` parameter comes from a PR and have not built and published yet.

**Comment by fengyuanchen** [comment]
It had been released.

**Comment by Vinze** [comment]
Great, thanks!
