### ISSUE TITLE
Cannot get vue.js data object updated in two-way data bindings

### ISSUE THREAD

**Issue by stratboy** [fengyuanchen/datepicker#165]
Hi, I'm having issues with vue's two-way data bindings and your plugin. I tried several ways but wasn't able to solve this. Basically, Vue won't update its data based on input's value after selecting a date. It seems like datepicker doesn't trigger an 'input' event. Though, I tried to trigger it manually on `hide.datepicker` or `pick.datepicker`, but it doesn't work. I think that's because input's value (`$(e.target).val()`) is still empty on those custom events.

``` html
<input name="project[deadline]" v-model="form.project.deadline" id="project-deadline" type="text" data-toggle="datepicker" value="" />
```

``` js
var vueapp = new Vue({
  el: '#form'
  ,data:{
    form:{
      ,project:{}
    }
  }
  ,mounted: function(){
    $('[data-toggle="datepicker"]').on('hide.datepicker', function (e) {
      console.log($(e.target).val()); // empty! (and same with pick.datepicker)
    }.bind(this));
  }
});
```

How to solve?

**Comment by pbonano** [comment]
Rather than using the event object (which doesn't seem to do anything), I've had more luck retrieving the datepicker value by selecting the input field directly like the following:

`
//using jQuery in this example...

var self = this;
$('#<id of input>').on('input', function () {
                self.Date = $('#<id of input>[data-toggle="datepicker"]').val();
 });`
