### ISSUE TITLE
Compatibility for IE8

### ISSUE THREAD

**Issue by tam424** [fengyuanchen/datepicker#167]
It seems to be not neccessary at all but I would like to enable a compatibility for IE8.
Looks like that the function Object.defineProperty is not compatible with IE8 but the rest of the code is working properly.
I tried to find out how to detect IE8 and set a seperate code for this. Should I try set try-catch for this? It looks like as not a good idea at all...

Update as of 10.07.2018:
I was able to find a very good solution by checking if Object.defineProperties is included. It is not included in IE8 so this is the solution. It also works in IE7 :O...

Thank you for your attention,
Tamir

**Comment by fengyuanchen** [comment]
I'm sorry. This plugin are not support IE8 now.
