### ISSUE TITLE
Problem with trigger

### ISSUE THREAD

**Issue by Maximoy** [fengyuanchen/datepicker#173]
Hi,
I am not an IT person but made the way to put your code into my website forms.
I am almost finished but I am stacked with the following issue:
Do not know how to make the calendar icon to trigger the calendar.
I know I should include some code on the "trigger" option but do not know how...
Could you help? Thanks.

This is actually the code I have:

<div class="form-group row">
    <label for="date" class="col-md-4 col-form-label">Date</label>
    <div class="col-md-8">
          <div class="input-group">
        <input type="text" name="date" id="date" class="form-control" data-toggle="datepicker" placeholder="Pick a date" required>
          <div class="input-group-append">
              <button type="button" class="btn btn-outline-secondary">
                <i class="far fa-calendar-alt" aria-hidden="true"></i>
              </button>
            </div>
          </div>
          <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
  <script>
    $(function() {
      $('[data-toggle="datepicker"]').datepicker({
          autoHide: true,
        filter: function(date) {
    if (date.getMonth() === 11 && [24, 31].includes(date.getDate())) {
      return false;
    }
  }   
      });    
    });      
  </script>         
  </div>  
  </div>

**Comment by webdo** [comment]
You need to put the data "toggle" in the code of the input you want to trigger the datepicker.
For example:
`<input type="text" name="date" data-toggle="datepicker">`

**Comment by Maximoy** [comment]
Excelent! thanks.

**Comment by webdo** [comment]
To help you more i will need the code of the input field you are using, preferably the whole form.

**Comment by webdo** [comment]
Take a look at this example: [https://jsfiddle.net/rm9hqp7z/](url)

Please note that if you choose to use the trigger, the datepicker won't be shown when you click on the input, only by the button.

Also note that if you have multiple date on the same page you need to instantiate them separately, as shown in the example.

**Comment by chiragnsuthar** [comment]
Multiple date id Trigger solution work for me.

var $datePickerId = $(DateId);
            $datePickerId.each(function () {        
            var currentId = $(this);
            currentId.datepicker({
                 format: 'mm/dd/yyyy',
                 autohide: true,
                 trigger: currentId.parent().find(".date-icon"),
                 autoPick: true,
            });
})
