### ISSUE TITLE
Filter two or more calendars

### ISSUE THREAD

**Issue by artyombobr** [fengyuanchen/datepicker#180]
Good afternoon. I have two fields on my page for entering the date. And during the filtering of the second calendar, the first calendar is also filtered.

> function filterDate(response, toggle) {
            var now = new Date();
            window.dateHide = response;
            if (dateHide == null) {
                dateHide = 0;
            }
            $(toggle).datepicker({
                filter: function(date) {
                    for (var i = 0; i<dateHide.length; i++) {
                            if ((date.getMonth()+1) == window.dateHide[i].month && (date.getDate() == window.dateHide[i].day)) {
                            return false;
                        }
                    }
                },
                language: 'ru-RU',
                startDate: now,
                autoHide: true
            });
        }

**Comment by fengyuanchen** [comment]
It seems you didn't separate the two datepicker in your logic.
