### ISSUE TITLE
Filter with 2 conditions

### ISSUE THREAD

**Issue by Maximoy** [fengyuanchen/datepicker#181]
Hi, 
Several months ago I got from you this code:

if (date.getMonth() === 11 && [24, 31].includes(date.getDate())) {
      return false;
    }

The code blocks Dec 24 and Dec 31.
I would need to add a condition that also disables Saturdays and Sundays (every month).
Could you help me?
Thanks

**Comment by fengyuanchen** [comment]
Why not just **try try try** it by yourself?

**Comment by Maximoy** [comment]
Because I am not a programmer not IT person.
It is very difficult to me to find out the way through your code to make the changes I need.
Anyway. If you can not help any more, that's fine. You have already done too much developing the code.
Thanks.

Regards,
Maximo Yedid
BA Tour Guide
www.BAtourguide.com.ar
