### ISSUE TITLE
filter disable current day

### ISSUE THREAD

**Issue by esipavicius** [fengyuanchen/datepicker#182]
Right now cannot disable current day in filter method

**Comment by fengyuanchen** [comment]
```js
$('input').datepicker({
  filter: function (date, view) {
      if (date.getDate() === (new Date()).getDate() && view === 'day') {
        return false;
      }
    },
});
```

**Comment by esipavicius** [comment]
> if (date.getDate() === (new Date()).getDate() && view === 'day') { return false; }

Same not working... It not disable current day.

![1](https://user-images.githubusercontent.com/7330677/47911136-59a4bb80-de9d-11e8-8a5f-96e0779741d6.png)
![2](https://user-images.githubusercontent.com/7330677/47911141-5c9fac00-de9d-11e8-8d82-261d0af71a08.png)
![3](https://user-images.githubusercontent.com/7330677/47911144-5dd0d900-de9d-11e8-88f6-3ecdd21f74a1.png)

**Comment by fengyuanchen** [comment]
Have you used the latest version?

**Comment by Mariana-Marica** [comment]
> ```js
> $('input').datepicker({
>   filter: function (date, view) {
>       if (date.getDate() === (new Date()).getDate() && view === 'day') {
>         return false;
>       }
>     },
> });
> ```

For version v1.0.10 the 'view' param from 'filter' function is not available, it's undefined because the HTML is loaded after filtering and besides days, also months, and years starting with a specific filtered date will also be disabled :( 
Is there a workaround for this?
