### ISSUE TITLE
All dates convert to 1900s when going from yy to yyyy format

### ISSUE THREAD

**Issue by kiwikoda** [fengyuanchen/datepicker#186]
Currently all dates supplied as two digits convert to a 1900s date. This doesn't make sense, as users will expect a date with a recent year such as 05/02/18 to convert to 05/02/2018 (not 05/02/1918).

This issue can easily be recreated on the website test page by entering the above date - when opeing the date selector you will see the year is set to 1918. 

This issue was also mentioned by @tam424 as part of another issue https://github.com/fengyuanchen/datepicker/issues/168 but this was not resolved as part of that issue.

I believe @tam424 was suggesting something like the following, which I also think would be the perfect solution to this issue:

If a two-digit year is entered that is less than or equal to the current year plus 10 (i.e. 18 + 10 = 28) then this year should be converted to a 2000s date (i.e. 20XX). Otherwise, if the year entered is higher than the current year plus 10 then it should be converted to a 1900s date.

**Comment by fengyuanchen** [comment]
I think a `05/02/18` value should be converted to `05/02/0018` when the format is `mm/dd/yyyy`.

**Comment by kiwikoda** [comment]
Hi Fengyuan

I have no doubt that anyone who enters a two-digit year that is less than 30 will be expecting that year to convert to a year in the 2000s.

Anyone who is dealing with dates in the first century such as the example you've given would always specify the year in four-digit format. And that would be the case with anything pre-1950s generally also.

It would be worth having a look around to see what others are doing. Here is the approach that IBM is taking with this problem for instance:

https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_73/rzase/yrconv.htm

I'm sure you will find many other examples as well.

John
