### ISSUE TITLE
Delayed set value vs Jquery Validation

### ISSUE THREAD

**Issue by mm98** [fengyuanchen/datepicker#188]
First of all, thanks for this awesome plugin. Great work!

I'm struggling a bit with this plugins in regards to jquery-validation. It seams like this plugin sets the picked date after the input change event is triggered. Which means, that jquery-validation (custom validation method) is triggered before the value has been set. This results in the validation method gets the previous value (date). Is there any way to ensure, that the value has been set - before the event is triggered?

This problem can be seen here (change modified date): [https://netcore.roob.dk/](https://netcore.roob.dk/) .. data is logged in console (devtools).

I know this might not be a bug.  Thanks in advance!

**Comment by fengyuanchen** [comment]
The change event is triggered after set value! [Here is the related code](https://github.com/fengyuanchen/datepicker/blob/master/src/js/methods.js#L109-L114).

**Comment by mm98** [comment]
> The change event is triggered after set value! [Here is the related code](https://github.com/fengyuanchen/datepicker/blob/master/src/js/methods.js#L109-L114).

The reason there is a delay is, because jquery validate uses `onfocusout` event. When a date is picked in the datepicker, the `onfocusout` event is firing before setValue(). Needed to add custom code to jquery validate, to get this working (100 ms delay before validate).
