### ISSUE TITLE
Datepicker won't hide on click when inside a dropdown

### ISSUE THREAD

**Issue by timbarclay** [fengyuanchen/datepicker#190]
If you put a datepicker inside a bootstrap dropdown, then the normal behaviour - where the datepicker hides if you click outside it - doesn't work.

See this jsfiddle https://jsfiddle.net/aq9Laaew/292990/

- Open the dropdown
- Click in the input to show the datepicker
- Click somewhere inside the dropdown but outside the input

I would expect the datepicker to hide but it doesn't.

**Comment by fengyuanchen** [comment]
The Bootstrap's [Dropdown.js](https://github.com/twbs/bootstrap/blob/v4-dev/js/src/dropdown.js#L266) called the `event.stopPropagation()` function, so the datepicker's click event listener will not be executed at all.
