### ISSUE TITLE
Dates typed in wrong format result in weird selection

### ISSUE THREAD

**Issue by eth8505** [fengyuanchen/datepicker#191]
![grafik](https://user-images.githubusercontent.com/1136509/50008684-436a3f00-ffb5-11e8-880c-80d5f37f0c82.png)

I have my format set to DD.MM.YYYY, I type a date in YYYY/MM/DD format, and the datepicker goes crazy. With 2018/01/02 it selects the july 11th 1907. I traced this to the date parser not actually respecting the format, but only the order of parameters defined in the format, interpreting 2018 as day, 01 as month and 02 as year. Imho the date parser should only accept exactly what is specified as format, there shouldn't be any format guessing. Especially, separators should not be ignored when trying to parse.

**Comment by fengyuanchen** [comment]
Duplicate to #186

**Comment by eth8505** [comment]
@fengyuanchen #186 does not fix bug I reported. If my format is DD.MM.YYYY and I type a YYYY/MM/DD date, I still get an incorrect selection. Imho the datepicker should ignore anything typed in a format the picker does not recognize. Would it be possible to disable the date guessing with a flag and have it only support the actual format specified?

**Comment by fengyuanchen** [comment]
@eth8505 Not support that. Please type a date follow the given format.

**Comment by eth8505** [comment]
@fengyuanchen the picker doesn't even follow the format, separators are ignored completely.
