### ISSUE TITLE
选择年份-通过两边和通过中间点击选择的问题

### ISSUE THREAD

**Issue by jcxwyh** [fengyuanchen/datepicker#193]
通过中间选择有效，通过两边的尖括号选择无效

**Comment by fengyuanchen** [comment]
能否描述清楚一点？

**Comment by jcxwyh** [comment]
就官网上我试了下也有这个问题，选择年份的时候，两种方式
一是年的左右两边往前一年往后一年的小按钮
二是直接点击年份，选择年

情况是通过第一种方式，年其实没有改，输入框里的年份还是原来的年份


比如我通过第一种方式已经选到了2017年，然后随便选个三月
但是输入框里显示的内容还是2018年3月

**Comment by jcxwyh** [comment]
在只选月的情况，比如yyyy-mm
