### ISSUE TITLE
wrong future month selection when today is 31 

### ISSUE THREAD

**Issue by alkaest2002** [fengyuanchen/datepicker#195]
Datepicker version: 1.0.3

Bug scenario:
```
Today is: 2018 December 31
From the "month view" I select: June 2019
The result is: July 2019
```

I think the bug is related to the current date (31) and the fact that June has 30 days

**Comment by ikeblaster** [comment]
This still seems to be a problem. :/ Doesn't matter if I switch to February first or I click the date right from January.

![test](https://user-images.githubusercontent.com/6796369/52048017-976fb980-254a-11e9-8352-7f48b9d421d9.gif)
