### ISSUE TITLE
Month and Year picker

### ISSUE THREAD

**Issue by kushal9291** [fengyuanchen/datepicker#196]
How can I use this as month/year picker? I tried setting format: 'mm/yyyy' and make it partially worked. 
However, it's not updating when I change years with navigation arrows. 
Thanks
Kushal
![screenshot 23](https://user-images.githubusercontent.com/16516005/50760808-c1f18e00-128e-11e9-9323-40f818b1b7a5.png)

**Comment by fengyuanchen** [comment]
You also need to pick a month for updating the value.

**Comment by kushal9291** [comment]
> You also need to pick a month for updating the value.

I picked the month. But the problem is it doesn't update the year which I changed through navigation.

**Comment by fengyuanchen** [comment]
I mean you need to pick a month for updating the value **after change the year through navigation**.

**Comment by kushal9291** [comment]
Sorry, Actually other scripts are interfearing otherwise it's working perfectly fine. Thanks for this great date picker :)
