### ISSUE TITLE
Iphones Safari - Datepicker does not hide onblur or focusOut of input field

### ISSUE THREAD

**Issue by fxvisuals** [fengyuanchen/datepicker#197]
On Iphones (Safari), when you click outside(focusOut) the calendar doesn't disappear.

**Comment by fengyuanchen** [comment]
It is still focusing in. Click another input then it will focus out and hide.

**Comment by fxvisuals** [comment]
It works when we click on another input but not working if we clicks outside of the field.

The issue is happening on Iphones (Safari) only and other browsers are working fine. 

How can we fix it? Please suggest.

**Comment by fxvisuals** [comment]
Hi there,

The datepicker is not hiding when click on inactive dates. Please see the screenshot for more info - https://www.screencast.com/t/wmMVX1qC

OR

How can we remove the inactive dates from the current month? like jQuery datapicker - https://jqueryui.com/datepicker/

Thanks,
