### ISSUE TITLE
Default Date Set

### ISSUE THREAD

**Issue by DevinWalker** [fengyuanchen/datepicker#2]
How can we set the default date value? For instance, when the user loads the page it should show today's date, in whichever format selected, by default.

**Comment by DevinWalker** [comment]
Ok so this is a little dirty but I got it working with:


	//Select default date
	$(window ).on('load', function(){

		$('.datepicker-days .selected' ).trigger('click');

	} );

**Comment by DevinWalker** [comment]
It would be great to have an option for this though :]

**Comment by anoopmd** [comment]
I agree too. It would be great to have that option.

**Comment by fengyuanchen** [comment]
The default value of a input element is the default date.

**Comment by anoopmd** [comment]
@fengyuanchen It would be great if we had an api to manually set the date after the datepicker is intantiated.

**Comment by fengyuanchen** [comment]
You can use `autopick` option in the v0.2.0 now.
