### ISSUE TITLE
how to set startDate for last year?

### ISSUE THREAD

**Issue by neoacevedo** [fengyuanchen/datepicker#205]
I try to set the startDate as **'-1y'** but it disables every date before current date.

How do I to set a start date from the last year?

**Comment by deybyd182** [comment]
You should use the date in dd/MM/yyyy format, example:

`$('.datepicker').datepicker('startDate ', '14/03/2018');`

this will work for sure!

**Comment by neoacevedo** [comment]
Amazing that must to be an exact date. The documentation is  a little inaccurate.
