### ISSUE TITLE
Input & Change events actually doesn't work

### ISSUE THREAD

**Issue by Julien-Marcou** [fengyuanchen/datepicker#214]
I know this issue as already been reported here #174 and there #188, but indeed, these events doesn't work (almost).

Using jQuery's trigger method, only triggers "jQuery" events, but not "native" events.
So if you use native JS to listen to change/input events, with "addEventListener", this will not work.

You should consider using native events :
```
input.dispatchEvent(new Event('change'));`
```

Meanwhile, for those who are searching for a solution, the best way to handle this at the moment, is to manually forward yourself the change event :

```
var previousValue = input.value;
$(input).on('change', function() {
  if (input.value !== previousValue) {
    previousValue = input.value;
    input.dispatchEvent(new Event('change'));
  }
});
```

We must save the previous value, so we only dispatch the event when the value as actually changed, otherwise it will create an infinite loop as the native "change" event also triggers the jQuery "change" event.

**Comment by fengyuanchen** [comment]
I think this is not a problem as it is just a jQuery plugin.

**Comment by cjboco** [comment]
I know this is a jQuery plug-in, but I have mix code on one of my projects (vanilla / jQuery)... so if anyone is looking for a quick solution, you can do this:


```
$( '[data-toggle="datepicker"]' ).datepicker( {
    'format': 'mm/dd/yyyy',
    'pick': function ( e ) {
        e.target.value = $().datepicker( 'formatDate', e.date );
        e.target.dispatchEvent( new Event( 'pick.datepicker' ) );
    }
} );
```

I was also having issue with the Vanilla JS not reading the value properly, hence I'm setting it as well. Seemed to fix the issue for me.

**Comment by fengyuanchen** [comment]
@Julien-Marcou After tested, both the native `input` and `change` events are triggered when you pick a date (after the `pick.datepicker` event).

**Comment by chiragnsuthar** [comment]
any option for add remove class?  

$('[data-toggle="datepicker"]').datepicker();
