### ISSUE TITLE
[NFR] Support Month names in datepicker format

### ISSUE THREAD

**Issue by temuri416** [fengyuanchen/datepicker#22]
Hi,

Thanks for the nice datepicker!

It would be nice to be able to format dates as:

`Feb 10, 2016`
and
`15 February 2016`

Cheers!

**Comment by fengyuanchen** [comment]
You can customize it by yourself with the API.

**Comment by kushal9291** [comment]
Hi,
I added the following code to achieve the same. But I'm not sure if it's the right way.
```
    $('.monthYearPicker').on('pick.datepicker', function (e) {
        e.preventDefault();  
        var monthDate = months[e.date.getMonth()] + ' ' + e.date.getFullYear();
        $(this).val(monthDate); 
    }); 
```
Thanks
