### ISSUE TITLE
Datepicker is not showing in model

### ISSUE THREAD

**Issue by kamna1992** [fengyuanchen/datepicker#221]
**Describe the bug**
I have created one model box inside one another model box and using your datepicker. I am using inline true feature for your datepicker. Js is working fine but the calendar is not showing.

I am using Modals - Materialize for model box.

Please help me asap. 
![datepicker](https://user-images.githubusercontent.com/30888722/64518635-267a5680-d310-11e9-95f5-afaa20b02e1b.png)

**Comment by gavin310** [comment]
I'm pretty sure that your problem is that the datepicker uses a relatively low z-index (1000). Set the datepicker to have a higher z-index than your modal and force it with !important.

> .datepicker-container { z-index: 99999 !important; }

**Comment by fengyuanchen** [comment]
Maybe you can destroy the datepicker after pick a date.
