### ISSUE TITLE
Problems with typing and 31

### ISSUE THREAD

**Issue by nicolez9911** [fengyuanchen/datepicker#222]
There seems to be some issue when you type in a date where the day is the 31. In this case, the value of getDate is the 1. of the typed in month (also selects the 1. in the datepicker).
I'm having the issue with german date format. It also happens with en-GB but not with en-US. (Probably bc day isn't the first value?).

Also happens on your website:
1. Select format dd/mm/yyyy
2. Type 31/10/2019 in the datepicker field
3. getDate will show the 1. of October

Thanks

**Comment by fengyuanchen** [comment]
`31/10/2019` is not a valid date as October only has 30 days.

**Comment by nicolez9911** [comment]
Doesn‘t matter which month, it‘s always the same behaviour with the all the 31.

**Comment by tombille** [comment]
> `31/10/2019` is not a valid date as October only has 30 days.

Well, my birthday is the 31st. of october, so must be a bug :)

**Comment by fengyuanchen** [comment]
It is my mistake. `31/10/2019` is a valid date.
