### ISSUE TITLE
setStartDate not working

### ISSUE THREAD

**Issue by Roi467** [fengyuanchen/datepicker#225]
Hello :) I tryed to set start date but unfortunately its not working
the startDate and setDate work

Im used the version: v1.0.8
Date release: 2019-06-23T08:07:40.545Z
`    $('[data-toggle="datepicker"]').datepicker({
        language: 'he-HE',
        startDate: '01/01/1920',
        setStartDate: '01/01/1920',
    });`

tnx :)

**Comment by tipsclick** [comment]
just use setStartDate: so it will effect on startDate:
example code
$('[data-toggle="datepicker"]').datepicker({ language: 'he-HE', setStartDate: '01/01/1920', });

**Comment by Roi467** [comment]
> just use setStartDate: so it will effect on startDate:
> example code
> $('[data-toggle="datepicker"]').datepicker({ language: 'he-HE', setStartDate: '01/01/1920', });

not work yet 

what its the cdn for this plugin I will upload to codepen

**Comment by tipsclick** [comment]
You can use these
https://fengyuanchen.github.io/datepicker/css/datepicker.css
https://fengyuanchen.github.io/datepicker/js/datepicker.js

**Comment by Roi467** [comment]
> https://fengyuanchen.github.io/datepicker/js/datepicker.js

Its the codepen tnx
https://codepen.io/roi467/pen/rNNBxJY

**Comment by tipsclick** [comment]
it is fixed now. you can check codepen  link below 
https://codepen.io/tipsclick/pen/OJJLXQB

**Comment by fengyuanchen** [comment]
The `setStartDate` is a method, not an option!
