### ISSUE TITLE
Remove $.isNumeric

### ISSUE THREAD

**Issue by gregmynetwire** [fengyuanchen/datepicker#227]
The getDayName and getMonthName functions of the plugin are using $.isNumeric which is deprecated as of jQuery 3.0

**Comment by fengyuanchen** [comment]
Are you sure? I don't see that in the docs: https://api.jquery.com/category/deprecated/

**Comment by gregmynetwire** [comment]
It appears there is some confusion on their end.  I came to it from using the migrate plugin.
The jQuery migrate plugin has it listed as deprecated.  https://github.com/jquery/jquery-migrate/blob/master/warnings.md
jQuery 3 has it listed as a breaking change. https://jquery.com/upgrade-guide/3.0/#breaking-change-jquery-isnumeric-and-custom-tostring
Thanks for your work. Great plugin!

**Comment by fengyuanchen** [comment]
It said `jQuery.isNumeric() ` has a breaking change as of v3.x, but not deprecate it.
