### ISSUE TITLE
Jquery is planning to depreciate $.isNumeric

### ISSUE THREAD

**Issue by john2014** [fengyuanchen/datepicker#23]
Jquery is planning to depreciate $.isNumeric. I noticed multiple functions using this. Is it possible to update the datepicker to remove $.isNumeric?

https://github.com/jquery/jquery/milestones/3.1.0

**Comment by fengyuanchen** [comment]
Will update Cropper when jQuery@3.0.0 has been released. Thanks~

**Comment by fengyuanchen** [comment]
`$.isNumeric` still exists in jQuery 3.0+
