### ISSUE TITLE
Add few days to second datepicker based on first datepicker

### ISSUE THREAD

**Issue by awariat** [fengyuanchen/datepicker#230]
I created 2 datepickers
I want to use one as base date . The second datepicker depend on the first one and I add 7 days to the date of first one.
When I initialize is all OK:
```
 $('#createInvoice-invoiceDate').datepicker('setDate', new Date());
  var todayPlus = new Date();
  todayPlus.setDate(todayPlus.getDate() + 7);
  $('#createInvoice-dueDate').datepicker('setDate', todayPlus);
```
... but if I fire event it makes on both the same date + 7 (it should keep on first chosen date)

```
$('#createInvoice-invoiceDate').on('pick.datepicker', function (e) {
  console.log(e.date)// this shows date correctly
  var todayPlus = e.date;
    todayPlus.setDate(todayPlus.getDate() + 7);
  $('#createInvoice-dueDate').datepicker('setDate', todayPlus);
    });
```
After event the dates are the same and 7 days after.

**Comment by fengyuanchen** [comment]
You are using the same date instance object! Just clone the previous date with `new Date(e.date)`.
