### ISSUE TITLE
How to show Month name when pick date.

### ISSUE THREAD

**Issue by superuoa** [fengyuanchen/datepicker#237]
Example hear.
![image](https://user-images.githubusercontent.com/24907648/77135406-75fac580-6a9d-11ea-9bb6-d69fa8e69511.png)

Thank you.

**Comment by fengyuanchen** [comment]
Not support that. You can reset the input value in your format after picked a date.

**Comment by superuoa** [comment]
> Not support that. You can reset the input value in your format after picked a date.

Thank chen.  I solved the problem by using events onChange.

**Comment by chenchuraviteja** [comment]
can you send me any examples
