### ISSUE TITLE
How to set current date?

### ISSUE THREAD

**Issue by bilalsaeed** [fengyuanchen/datepicker#239]
Hi,

I am trying to set current date but it is not working. Following is my code.

```
$('[data-toggle="datepicker"]').datepicker({
        date: new Date(),
        autoPick: true
    }).datepicker('setDate', new Date(2020, 7, 6));
```

**Comment by IvicaPizent** [comment]
Hi,

Did you try to put date you want inside new Date(). Example from docs below.

```
$().datepicker({
  date: new Date(2020, 7, 6)
});
```

**Comment by fengyuanchen** [comment]
@bilalsaeed You might not use it in the right way, just check your own code carefully.

**Comment by bilalsaeed** [comment]
Thanks got it working.
