### ISSUE TITLE
How to get 'endDate'

### ISSUE THREAD

**Issue by anniephlf** [fengyuanchen/datepicker#244]
My apologies if this has already been asked or is a primitive question as I'm still new to javascript/jquery.  How would one get the datePicker's endDate value?  I had tried the following syntax but to no avail.  Thanks!

var test = $("#PreviousMembership_LastActivityDate").datepicker("options", "endDate");

**Comment by fengyuanchen** [comment]
```js
// Get the datepicker instance
var datepicker = $("#PreviousMembership_LastActivityDate").data("datepicker");
// console.log(datepicker);

// Get the end date
var endDate = datepicker.endDate;
```
