### ISSUE TITLE
date format "DD, MM d, yy"    Thursday, January 7, 2021   is not working 

### ISSUE THREAD

**Issue by nettycoons-soft-team-hp** [fengyuanchen/datepicker#250]
date format "DD, MM d, yy"    Thursday, January 7, 2021   is not working 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fengyuanchen** [comment]
This plugin only supports some limit format tokens, check out the `format` option for details: https://github.com/fengyuanchen/datepicker#format
