### ISSUE TITLE
Month and Year selection disabled based on filter (Day)

### ISSUE THREAD

**Issue by CsProgrammer05** [fengyuanchen/datepicker#251]
I wanted to disable Monday and Thursday in the calendar, with the following code:

`$(".DateBlock").datepicker({`
`autoShow:true,`
`filter: function(date) {`
` if(date.getDay() == 1 )`
`return false;`
` else if(date.getDay() == 4)`
`return false;`
`}`
`});`

_Datepicker v0.6.4_

It did disable Mondays and Thursday

![block-days](https://user-images.githubusercontent.com/82739529/115131411-9099c800-a02a-11eb-9b52-c7926d99dc02.png)

However, in the Month and Year selection got disabled also.

![month](https://user-images.githubusercontent.com/82739529/115131412-94c5e580-a02a-11eb-81bf-3ee0a7e77f7d.png)
![year](https://user-images.githubusercontent.com/82739529/115131443-c048d000-a02a-11eb-9c83-7c64b916ab87.png)

What did I do wrong? how do i fix this? Is there another way I can implement this?
Thanks.

**Comment by fengyuanchen** [comment]
Please upgrade to the latest version, and use the second parameter of the `filter` option to disable only the `day` view:

```js
$(".DateBlock").datepicker({
  autoShow:true,
  filter: function (date, view) {
    if (view === "day" && (date.getDay() == 1 || date.getDay() == 4)) {
      return false;
    }
  }
});
```
