### ISSUE TITLE
starDate does not disable days before today

### ISSUE THREAD

**Issue by jonasmarco** [fengyuanchen/datepicker#254]
I would like to start a calendar by disabling dates before today. Using the **startDate** option didn't work for me.

```javascript
$startDate.datepicker({
    autoHide: true,
    format: 'dd/mm/yyyy',
    language: 'pt-BR',
    startDate: new Date(),
});
```

**Comment by fengyuanchen** [comment]
It works fine in my demo. Just try to debug it by yourself.
