### ISSUE TITLE
Date format taking as dd-mm-yyyy even though format config is given as yyyy-mm-dd

### ISSUE THREAD

**Issue by prithwirajbose** [fengyuanchen/datepicker#255]
I am initializing the datepicker with simple config, just provided the format attribute. It fails to follow the format I've specified. Following is the code used to initialize the Date Picker:

```
$('.datepicker').datepicker({
	"format": "yyyy-mm-dd"
});
```
But on the webpage I see the input field is populated as dd-mm-yyyy by the Datepicker.

**To Reproduce**
Included following line in Document body:
```
<script type="text/javascript" src="js/datepicker.common.js"></script>
<script type="text/javascript" src="js/datepicker.min.js"></script>
<link rel="stylesheet" type="text/css" href="css/datepicker.min.css">
```

The inside a script tag, added following code:
```
$(document).ready(function() {
  $('.datepicker').datepicker({
	  "format": "yyyy-mm-dd"
  });
});
```

**Expected behavior**
The Datepicker should use the format specified, i.e. yyyy-mm-dd

**Screenshots**
[Screenshot of browser output](https://pasteboard.co/YT7xmvfWGNlM.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 95.0.4638.69 (Official Build) (64-bit)

**Comment by fengyuanchen** [comment]
It seems your case can't be reappeared in the official demo: https://fengyuanchen.github.io/datepicker/

**Comment by fengyuanchen** [comment]
And you seem to include the main file twice:

```html
<!-- Just remove `datepicker.common.js` file -->
<!-- <script type="text/javascript" src="js/datepicker.common.js"></script> -->
<script type="text/javascript" src="js/datepicker.min.js"></script>
<link rel="stylesheet" type="text/css" href="css/datepicker.min.css">
```
