### ISSUE TITLE
The datepicker not responsive on mobile devices

### ISSUE THREAD

**Issue by kanachrisi** [fengyuanchen/datepicker#256]
**Describe the bug**
Hello,
I am not able to use the datapicker on mobile devices,
The datapicker opens but when i resize the screen, it does
adjust to the screen size.

I don't know if i am missing some settings or i have to make it
responsible by myself.

Thank for the feedback

**Comment by fengyuanchen** [comment]
This jQuery plugin has been deprecated. Please search for a mobile-friendly datepicker for your case.
