### ISSUE TITLE
Use js import/require instead of script tag

### ISSUE THREAD

**Issue by MarkusHeinisch** [fengyuanchen/datepicker#259]
I dont want to use the html-script tag:
`<script src="https://fengyuanchen.github.io/datepicker/js/datepicker.js"></script>`

Instead i want to use the JS (node_modules) import or require statement in my webpack project with jquery.  Currently i use `import '@chenfengyuan/datepicker';` but i'am getting this error message "dateFrom.datepicker is not a function".

`const dateFrom = myform.find('[name="from"]');
dateFrom.datepicker({
			...datePickerConfig,
		});`

What i'am doing wrong?

**Comment by fengyuanchen** [comment]
This datepicker had been deprecated.

**Comment by fengyuanchen** [comment]
If you still want to use this, try this:

```js
import 'jquery';
import '@chenfengyuan/datepicker';
```
