### ISSUE TITLE
Dynamic options?

### ISSUE THREAD

**Issue by bjo3rnf** [fengyuanchen/datepicker#29]
Hi,

I need to update `startDate` and `endDate` dynamically on two datepickers that form a daterange picker. Currently I destroy and re-initialize the datepicker instances when the date range changes. Is there a better solution? jQueryUI's datepicker can be updated like this but I'd like to stick to yours.

Thanks in advance.

Cheers
Björn

**Comment by fengyuanchen** [comment]
Just use the `setStartDate` and `setEndDate` to update it.

**Comment by fengyuanchen** [comment]
Just use the `setStartDate` and `setEndDate` methods to update it.

**Comment by bjo3rnf** [comment]
Ah, nice. Thanks!
