### ISSUE TITLE
autoHide doesn't work when picking another month's day

### ISSUE THREAD

**Issue by gabrielps** [fengyuanchen/datepicker#41]
When choosing a date that is not from the month shown, the datepicker doesn't hides.

**Comment by gabrielps** [comment]
Btw, nice plugin. Love it's simplicity. If you want, I can try to resolve this issue on my spare time ;)

**Comment by fengyuanchen** [comment]
What do you mean of the another month's day?

**Comment by gabrielps** [comment]
"When choosing a date that is not from the month shown." Let's say you are on December 2016 and you click on January 1st 2017. 
![image](https://cloud.githubusercontent.com/assets/1233288/21520583/c218fe30-ccf5-11e6-9b24-1e4b048c4970.png)

**Comment by fengyuanchen** [comment]
It is the default behaviour of the datepicker.
