### ISSUE TITLE
Update method issue?

### ISSUE THREAD

**Issue by K-Thompson** [fengyuanchen/datepicker#47]
Thank you for a wonderful jQuery plugin. I think it will be very useful.

I'm having an issue with the 'update' method and wondered it this is expected behavior.

The markup includes an `input` element. The user can either type in the date or use your datepicker. If the user types the date, the datepicker reflects correctly the new date when opened. All is good.

However, if the user first sets a new date via the datepicker and then the `input` element's value is programmatically reset via JavaScript followed by a call to datepicker's `update` method to sync the datepicker with the element's date, the datepicker's calendar does not reflect the element's programmatically set date. The issue is, if the user sets the date in datepicker with a mouse click `update` does not seem to work if the element's value is programmatically changed.

Note, `setDate` works fine to resync the datepicker with the element.

**Comment by fengyuanchen** [comment]
Be sure that the input element' value must be changed (set a different and valid date string value) before call `update` method, if not, nothing will happen.
