### ISSUE TITLE
Check if just exists

### ISSUE THREAD

**Issue by ilvalerione** [fengyuanchen/datepicker#48]
Hello, 
I need to include this plugin dynamically into a webpage. I would check if another instance of plugin is just used in this external webpage and if it's not just exists proceed to include script.

Is there a line of code to check if plugin is just available on the page? 

Thanks for your support.

**Comment by fengyuanchen** [comment]
```js
  if ($.fn.datepicker) {
    // The plugin had been included.
  }
```
