### ISSUE TITLE
Datepicker floating above at a height when we select month or year view

### ISSUE THREAD

**Issue by vickylance** [fengyuanchen/datepicker#49]
When the datepicker comes at the bottom of input field its not an issue, but when the datepicker floats on the top of the input field and then we choose the month or the year view the datepicker does not adjust its position to match the position of the input field.
![er1](https://cloud.githubusercontent.com/assets/5861833/21923312/58c961e4-d999-11e6-8d6a-56ac2fa13fbd.PNG)
in the above image its ok
but when we choose the year of month view
![er2](https://cloud.githubusercontent.com/assets/5861833/21923327/6fb78e12-d999-11e6-9839-9480a325f587.PNG)
![er3](https://cloud.githubusercontent.com/assets/5861833/21923328/6fb809aa-d999-11e6-8618-acd615e919e1.PNG)
as you can see the entire datepicker is floating aloft

**Comment by fengyuanchen** [comment]
Thanks~
