### ISSUE TITLE
How to apply trigger when multiple instances of datepicker occur on the page?

### ISSUE THREAD

**Issue by oshihirii** [fengyuanchen/datepicker#51]
Hello,

How to apply trigger when multiple instances of datepicker occur on the page?  Eg:

**HTML**
```
<input class="my_class" id="my_date_01" name="my_name_01" data-toggle="datepicker"><i class="fa fa-calendar datepicker_trigger" aria-hidden="true"></i>

<input class="my_class" id="my_date_02" name="my_name_02" data-toggle="datepicker"><i class="fa fa-calendar datepicker_trigger" aria-hidden="true"></i>
```

**JS**
```
$('[data-toggle="datepicker"]').datepicker({
  autoHide: true,
  trigger: ".datepicker_trigger",
  format: 'dd/mm/yyyy',
  daysShort: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
});
```

Currently, the above opens several `datepicker` interfaces.

Thank You.  

**Edit:**  
I looked through the code to try and find where the `show` was applied in the hope that I could `show` just the closest instance of datepicker when clicking on a trigger (or even the `index()` of datepicker that matched the trigger's `index()`) but I couldn't figure out how to do it.

**Comment by fengyuanchen** [comment]
This is a question of how to use jQuery exactly.

**Comment by skypirates17** [comment]
same issue encountered... i think we should reopen this issue, or create new one

**Comment by skypirates17** [comment]
i also encountered this issue..
