### ISSUE TITLE
pick  event  has delay-trigger problem   pick事件触发时间不对

### ISSUE THREAD

**Issue by HectorChow** [fengyuanchen/datepicker#55]
每次选中日期后，选择框隐藏后pick不触发，第二次选择后才会触发上一次的事件。麻烦验证下是否这个问题，或是我用法有问题

**Comment by HectorChow** [comment]
$("input[name='BeginDate']").datepicker('pick', function (e) {

        var begindate = e.target.value;

        $(this).parent().next().find("input").datepicker('setStartDate',begindate);

    });

**Comment by fengyuanchen** [comment]
这。。。你的用法有问题！
