### ISSUE TITLE
How to make linked datepicker?

### ISSUE THREAD

**Issue by kunalvirk** [fengyuanchen/datepicker#57]
How to make a linked date picker ex. FROM DATE to TO DATE.

**Comment by alexanderzinolidis** [comment]
Why was this closed? I think this is a good question.

**Comment by fengyuanchen** [comment]
@alexanderzinolidis I don't understand that question. More detail?

**Comment by srijaydeathwish** [comment]
@fengyuanchen Yes this is a good question. @kunalvirk wanted to make a linked datepicker, like how they have in hotel booking websites for check-in and check-out picker. Basically when first date is picked from one picker, second picker automatically updates by disabling dates picked by first picker.

**Comment by fengyuanchen** [comment]
I think the `pick` event can be used to sync the two picker.

**Comment by srijaydeathwish** [comment]
`var today = new Date();
var date = today.getDate() + '-' + (today.getMonth() + 1) + '-' + today.getFullYear();
//console.log(date);
$("#sdate").datepicker({
  format: "dd-mm-yyyy",
  autoHide: true,
  startDate: date,
  pick: function (dt, inst) {
    var date2 = $('#sdate').datepicker('getDate');
    console.log(date2);
    date2.setDate(date2.getDate() + 1);
    $("#edate").datepicker({
      format: "dd-mm-yyyy",
      startDate: date2,
      autoShow: true,
      autoHide: true,
    }).datepicker('setDate', date2);
    //$('#edate').datepicker('setDate', date2);
  }
});
`
@fengyuanchen  I tried this way. Its working when i select date for first time. But when i select date in first picker which is lesser than previously selected date, second datepicker isnt updating.
