### ISSUE TITLE
[Docs bug + enhancement request] Date ranges

### ISSUE THREAD

**Issue by djkirby** [fengyuanchen/datepicker#6]
In the docs you have for setting a date range:

`var now = Date.now();`

`$("#datepicker-disable-past").datepicker({`
`    isDisabled: function(date) {`
`        return date.valueOf() < now ? true : false;`
`    }`
`});`

`date.valueOf()` is at midnight and we're comparing that to right now today, so this can lead to disabling the current day when it shouldn't. My solution was something like:

`return date.valueOf() <= Date.now() - 1000 * 60 * 60 * 24;`

Edit: it would be even better if there were `minDate` and `maxDate` options for the API

**Comment by fengyuanchen** [comment]
The documentation has updated to v0.2.0 now.
