### ISSUE TITLE
ReferenceError: require is not defined

### ISSUE THREAD

**Issue by littlestninja** [fengyuanchen/datepicker#62]
I REALLY want to use your excellent plugin as it's such an elegant solution, but I'm following your 'download the latest release' method: including the files in the head of my project, including jquery and initiating using `$('[data-toggle="datepicker"]').datepicker();` on document load in and all I get is:

`ReferenceError: require is not defined`

I don't have the know-how/access to install it via one of the three 'quick start' methods and was wondering if I was missing something? As far as I can tell I'm doing everything your installation instructions are requiring.

Many thanks!

**Comment by littlestninja** [comment]
I should say I am including the `datepicker.min.js` and `datepicker.css` both from the 'dist' folder in the download.

**Comment by HectorChow** [comment]
Obviously, the error prompt means the object or  variable 'require' is not defined.It isn't about  the plugin. U should show some code.

**Comment by littlestninja** [comment]
I understand what you're saying but it is the plugin that is throwing the error. I do not use 'require' anywhere else in my site. It is a codeigniter based PHP and html site with JQuery. If I don't include the plugin, no errors, when I do include it (exactly as instructed) it shows this error, and it's being thrown from line 17 of datepicker.js. There isn't a list of requirements on the datepicker site so it should just run, so why isn't it?

**Comment by littlestninja** [comment]
It looks to me that it might be expecting you to be using requirejs, and I'm not (and wouldn't know how to!) I just want tot include it in my simple site and use it!

**Comment by arxeiss** [comment]
If it is still actual, just download scripts from `dist` folder, not any others. I don't use `require` and it works perfectly.
