### ISSUE TITLE
Using trigger disables input activation?

### ISSUE THREAD

**Issue by cibgraphics** [fengyuanchen/datepicker#70]
Perhaps my thinking is wrong on this, but correct me if I am wrong. The trigger works as expected, but the input no longer triggers the calendar. Was this intentional or am I doing something incorrectly? If this is intentional, is there a way to have both the input and trigger have the calendar popup

```
<div class="field">
  <label>Birth Date</label>
  <div class="has-icon">
    <input type="text" data-toggle="datepicker">
    <i class="icon-calendar-o"></i>
  </div>
</div>
```

```
$('[data-toggle="datepicker"]').each(function() {
  var $this = $(this);

  $this.datepicker({
    format: 'mm/dd/yyyy',
    autoHide: true,
    trigger: $this.siblings("i"),
  });
});
```

**Comment by fengyuanchen** [comment]
Yes, it is designed as this.

**Comment by fengyuanchen** [comment]
For your case, you can ignore the `trigger` option and custom your own trigger, such as:
```html
<input type="button" id="datepicker" name="date">
<label for="datepicker">Custom trigger</label>
```
