### ISSUE TITLE
autoHide has no effect when selecting muted item

### ISSUE THREAD

**Issue by mm98** [fengyuanchen/datepicker#74]
Hi,

When using the **datepicker** with the following options: `autoHide: true, autoPick: true`. Days from the previous or next month has the CSS class `muted` defined. These can be selected (input is updated with selected date), but the `autoHide` option has no effect on these. Is this by design or possible an bug?

**[click](https://github.com/fengyuanchen/datepicker/blob/master/src/datepicker.js#L983)** function only hides the view, if the clicked item `view` equals `day`.

> if (view === 'day') {
	this.hideView();
}

`muted` items has either `day prev` or `day next` defined. 

**Possible solution:**
Either the view check could be removed or `day prev` ([here](https://github.com/fengyuanchen/datepicker/blob/master/src/datepicker.js#L730)) and `day next` ([here](https://github.com/fengyuanchen/datepicker/blob/master/src/datepicker.js#L776)) items could have `disabled: true` defined (not ux friendly).

**Comment by fengyuanchen** [comment]
It is designed as this.
