### ISSUE TITLE
After date is set programattically, when we click it again - it doesn't change

### ISSUE THREAD

**Issue by sergiy24ok** [fengyuanchen/datepicker#80]
Options checked: inline, container

1. Change date programatically to 31 july 2017: $('.docs-date').datepicker('setDate', new Date('2017-07-31'))

2. Select other date by clicking

3. Click on 31 July 2017 - it doesn't change !!!

Demo: https://youtu.be/dB4V-1qvyrQ

**Comment by fengyuanchen** [comment]
This is similar as #75.
