### ISSUE TITLE
feature-request: add of custom container class

### ISSUE THREAD

**Issue by Lor-Saba** [fengyuanchen/datepicker#81]
A parameter which adds (NOT replace) a class to the *.datepicker-container* element would be of great use.
Something like:  `$().datepicker({ containerClass: "foo" });`  

This would make it possible to differentiate and link each initialized datepicker elements in case of multiple initializations on the same page.   

Usage example: The datepicker "A" should have a different css style of the datepicker "B"

**Comment by fengyuanchen** [comment]
Just use the datepicker to do it:

```js
$('input').datepicker();

var datepicker= $('input').data('datepicker');

datepicker.$picker.addClass('foo');
```

**Comment by Lor-Saba** [comment]
Oh! I had not seen that property. Thank you for the reply and for the example.
