### ISSUE TITLE
feature-request: label format more customizable 

### ISSUE THREAD

**Issue by Lor-Saba** [fengyuanchen/datepicker#82]
The current [format](https://github.com/fengyuanchen/datepicker#format) property can handle only a `String` as argument to set the label output format, 
like: *'mm/dd/yyyy'* or *'dd/mm/yyyy'* and so on.

Could you add the ability to pass a `function` too? 
This way the output can be manipulated more freely.

Something like:

```javascript
$().datepicker({
    // _date contains the current or picked date (Date constructor)
    format: function(_date){ 
        return _date.getDate() +'/'+ _date.getMonth() +'/'+ _date.getFullYear();
    }
});
```

My use case: 
I'm using "moment.js" to handle the dates, with the above example I could parse the output like this:

```javascript
$().datepicker({
    format: function(_date){
        return moment(_date).format('ll');
    }
});
```

**Comment by fengyuanchen** [comment]
You can implement it by yourself.

**Comment by cliftonscott** [comment]
@fengyuanchen  Any suggestions on how to implement this ourselves? Thank you!
