### ISSUE TITLE
How to avoid user to input the date?

### ISSUE THREAD

**Issue by NingerJohn** [fengyuanchen/datepicker#84]
Is there any configuraton to avoid user input the non-date format characters?

**Comment by twhitacre** [comment]
@NingerJohn I just had that problem and came here to see if there was a solution. 

I ended up solving it by adding an `eventListener` for `keypress` on the field and preventing default. That way, they can still chose a date and click on the input field, but can't actually type in the box.

Probably a better solution out there, but it was a quick fix that kept me moving.

**Comment by fengyuanchen** [comment]
Just control it with native events as `mousepress` and `input`.
