### ISSUE TITLE
Datepicker arrow is displayed away from targeted element

### ISSUE THREAD

**Issue by Mariana-Marica** [fengyuanchen/datepicker#87]
I attached an image with the specific case when this occurs: below calendar image there is not enough space for the datepicker window to be displayed, thus appearing above the icon; but the arrow is displayed above the datepicker window; how do i position the datepicker arrow to be displayed near the calendar icon ?
![pic](https://user-images.githubusercontent.com/24438362/29915597-f27899f8-8e44-11e7-9941-53bd4c87c48f.png)

**Comment by fengyuanchen** [comment]
It seems you had customized the datepicker in your own theme, you might have to find out the problem by yourself.
