### ISSUE TITLE
README.md - Usage

### ISSUE THREAD

**Issue by medskill** [fengyuanchen/datepicker#88]
Hello, 
the usage part in the readme file hasn't all needed code :
`$('[data-toggle="datepicker"]').datepicker();`

should be : 
```
<script>
$(function() {
    $('[data-toggle="datepicker"]').datepicker();
});
</script>
```

Thanks for your time

**Comment by fengyuanchen** [comment]
As this is a jQuery plugin, the users are expected to know the basic usage of jQuery syntax.
