### ISSUE TITLE
Date become Undefined NaN when month change

### ISSUE THREAD

**Issue by Meorne** [fengyuanchen/datepicker#94]
When the year change with month's arrow, the date bug and become Undefined NaN 
![image](https://user-images.githubusercontent.com/13867541/30903980-ca4c5bd6-a370-11e7-9aaf-efc74e8af29b.png)

More detail:
https://imgur.com/a/Kenhu

**Comment by Jaspur** [comment]
@fengyuanchen same here, but when i go to the next year.. 2018

**Comment by mrl0wskill** [comment]
same here, but also when i go back to year 2016.

**Comment by unsaame** [comment]
@fengyuanchen yes indeed, can see the same error! :-(

**Comment by Jaspur** [comment]
Can’t find where it goes wrong. Hopefully @fengyuanchen can fix it after he wakes up ;-)

**Comment by alitinker** [comment]
> same here, but when i go to the next year.. 2018

Happening to me too.

**Comment by florent-dehanne** [comment]
Thanks to @alitinker, I write a quick fix that solve this error.
After line 646 in datepicker.js, you can add this : 

`if (view === 'month prev' && viewMonth == -1)
{
    viewMonth = 11;
    viewYear = viewYear - 1;
}

if (view === 'month next' && viewMonth == 12)
{
    viewMonth = 0;
    viewYear = viewYear + 1;
}`

**Comment by Jaspur** [comment]
@florent-dehanne yep, that works! why not send in a PR? ;-)
