### ISSUE TITLE
Docs-date not working in modal inside

### ISSUE THREAD

**Issue by bangtiray** [fengyuanchen/datepicker#98]
Hi. i have trouble show datepicker class docs-date inside modal,, 
on page success for view datepicker but not in modal,, 

thanks before,,
anyway good plugin

**Comment by fengyuanchen** [comment]
Just set the `zIndex` option to a large number as `2048`.

**Comment by bangtiray** [comment]
Yes thank for solution.

Im adding some style for z-index..
And success docs-date..
Thanks.
