### ISSUE TITLE
Playground/CodePen example for datapicker with Bootstrap 4

### ISSUE THREAD

**Issue by whitneyland** [fengyuanchen/datepicker#99]
Need a playground sample for testing and experimentation, like something that runs on https://codepen.io, fiddler, or a similar site.

If you have one please reply and provide a link.  If not, I'll set one up and share it here for others to use.

Btw, I also assume there is no CDN url, other than using the site links:
https://fengyuanchen.github.io/datepicker/css/datepicker.css
https://fengyuanchen.github.io/js/common.js
https://fengyuanchen.github.io/js/datepicker.js

Thanks-

**Comment by whitneyland** [comment]
Ok here it is:
https://codepen.io/whitneyland/pen/XeeKjg

This makes is easy to experiment with the control in a playground environment.

**Comment by fengyuanchen** [comment]
Playground: https://fengyuanchen.github.io/datepicker/

**Comment by whitneyland** [comment]
That’s a great page as a demo! However would you agree it doesn’t let you use the date picker in a playground environment?  

The idea is to make it instantly hackable.  Instantly try out options, styliing, examples.   This let’s people quickly see how they can benefit in their particular situation.
